services:
  adeptusboticus:
    image: adeptusboticus
    build:
      context: .
      dockerfile: src/AdeptusBoticus/Dockerfile
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - WH40K_ID=${WH40K_ID}
      - AOS_ID=${AOS_ID}
      - HH_ID=${HH_ID}
      - BB_ID=${BB_ID}
      - ORDERS_ID=${ORDERS_ID}
    ports:
      - "80:80"
    env_file:
      - .env
    networks:
      - botnet
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - botnet
    volumes:
      - mongo_data:/data/db

networks:
  botnet:
    driver: bridge
   
volumes:
  mongo_data:
